spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.117.231:3368/liuyang_api?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.flow.demo.pojo